  - name: Add zalando postgres-operator-charts repo
    kubernetes.core.helm_repository:
      name: postgres-operator-charts
      repo_url: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    delegate_to: localhost
    changed_when: false

  - name: install zalando postgres-operator chart
    kubernetes.core.helm:
      name: "{{ POSTGRES_OPERATOR_NAME }}"
      chart_ref: postgres-operator-charts/postgres-operator
      update_repo_cache: yes
      wait: no
      chart_version: "{{ POSTGRES_OPERATOR_CHART_VERSION }}"
      kubeconfig: "{{ kubeconfig }}"
      namespace: "{{ OPERATOR_NAMESPACE }}"
      release_namespace: "{{ OPERATOR_NAMESPACE }}"

  - name: User Cluster Role
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      namespace: "{{ OPERATOR_NAMESPACE }}"
      template: clusterrole.yml.j2

  - name: remove old User Cluster Role Binding
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      api_version: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: postgres-user
      state: absent
      wait: yes

  - name: User Cluster Role Binding
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      template: clusterrole_binding.yml.j2
    with_items: "{{ OPERATOR_SERVICE_ACCOUNTS }}"
    loop_control:
      label: "{{ item.name }}"
