POSTGRES_NAME: edusharing-postgresql
POSTGRES_APP: edusharing
POSTGRES_DATABASES:
  postgresql: postgresql
POSTGRES_USERS:
  postgresql: 
    - createdb
POSTGRES_INSTANCE_COUNT: 1
POSTGRES_PATRONI_SYNC_MODE: true
POSTGRES_PATRONI_SYNC_MODE_STRICT: true
POSTGRES_SERVER_VERSION: "13"
POSTGRES_SERVER_PARAMS: 
  - "max_connections: \"300\""
POSTGRES_PVC_SIZE: 5Gi
POSTGRES_PVC_CLASS: ionos-enterprise-hdd
POSTGRES_LIMITS_CPU: 4000m
POSTGRES_LIMITS_MEMORY: 8Gi
POSTGRES_REQUESTS_CPU: 100m
POSTGRES_REQUESTS_MEMORY: 256Mi
