---
name: Deploy Operators

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          python3 -m pip install kubernetes
      - run: ansible-galaxy install -r ansible/collections/requirements.yml
      - working-directory: ${{github.workspace }}/ansible/roles/sys-operator
        run: |
          mkdir files
          echo "${{ secrets.DEV_CLUSTER }}" > files/config
      - run: ansible-playbook ./playbook_operator.yml --inventory-file hosts --limit "develop" -e 'ansible_python_interpreter=/usr/bin/python3'
        working-directory: ${{github.workspace }}/ansible
      - working-directory: ${{github.workspace }}/ansible/roles/sys-operator/files
        run: |
          rm -rf  /config
