---
name: Build and push Docker Image on Tag for netperf

on:
  push:
    tags:
      - 'netperf/[0-9]*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-netperf
          tags: |
            type=match,pattern=netperf/(\d.\d.\d),group=1

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./k-bench/netperf/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}
