   ## helpers, small scripts for maintenance
  - name: create dir .kube
    file:
      path: "{{ ansible_env.HOME }}/.kube/"
      state: directory
      mode: 0700
      
  - name: push kubeconfig
    copy:
      src: "{{ kubeconfig_yml }}"
      dest: "{{ ansible_env.HOME }}/.kube/config"
      mode: 0600
    when: kubeconfig_yml is defined
    
  - name: push kubeconfig
    copy:
      src: config
      dest: "{{ ansible_env.HOME }}/.kube/config"
      mode: 0600
    when: kubeconfig_yml is undefined
    
  - name: Namespace
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ OPERATOR_NAMESPACE }}"
      template: namespace.yml.j2